{
    "id": "df33d690-4451-422f-83e0-3188611f3e00",
    "createdDateTime": "2022-06-30T09:33:27Z",
    "userDisplayName": "Victim",
    "userPrincipalName": "victim@securathesis.onmicrosoft.com",
    "userId": "ead0ddd5-9e3e-4430-97de-e1d123506b73",
    "appId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "appDisplayName": "Microsoft Azure CLI",
    "ipAddress": "<Redacted>",
    "ipAddressFromResourceProvider": null,
    "clientAppUsed": "Mobile Apps and Desktop clients",
    "userAgent": "python-requests/2.26.0",
    "correlationId": "2f45bd50-86cc-4a0d-9e70-9fec7e206d83",
    "conditionalAccessStatus": "notApplied",
    "originalRequestId": "",
    "isInteractive": true,
    "tokenIssuerName": "",
    "tokenIssuerType": "AzureAD",
    "clientCredentialType": "none",
    "processingTimeInMilliseconds": 106,
    "riskDetail": "hidden",
    "riskLevelAggregated": "hidden",
    "riskLevelDuringSignIn": "hidden",
    "riskState": "none",
    "riskEventTypes_v2": [],
    "resourceDisplayName": "Windows Azure Service Management API",
    "resourceId": "797f4846-ba00-4fd7-ba43-dac1f8f63013",
    "resourceTenantId": "d2af6ef7-a00c-438f-903b-65592cfddc48",
    "homeTenantId": "d2af6ef7-a00c-438f-903b-65592cfddc48",
    "homeTenantName": "",
    "authenticationMethodsUsed": [],
    "authenticationRequirement": "singleFactorAuthentication",
    "signInIdentifier": "victim@securathesis.onmicrosoft.com",
    "signInIdentifierType": null,
    "servicePrincipalName": null,
    "signInEventTypes": [
        "interactiveUser"
    ],
    "servicePrincipalId": "",
    "federatedCredentialId": null,
    "userType": "member",
    "flaggedForReview": false,
    "isTenantRestricted": false,
    "autonomousSystemNumber": 12859,
    "crossTenantAccessType": "none",
    "servicePrincipalCredentialKeyId": null,
    "servicePrincipalCredentialThumbprint": "",
    "uniqueTokenIdentifier": "ZGYzM2Q2OTAtNDQ1MS00MjJmLTgzZTAtMzE4ODYxMWYzZTAw",
    "incomingTokenType": "none",
    "authenticationProtocol": "none",
    "resourceServicePrincipalId": "342a9ec4-8650-445e-ac63-489df0a9e524",
    "mfaDetail": null,
    "status": {
        "errorCode": 50126,
        "failureReason": "Error validating credentials due to invalid username or password.",
        "additionalDetails": "The user didn't enter the right credentials.  It's expected to see some number of these errors in your logs due to users making mistakes."
    },
    "deviceDetail": {
        "deviceId": "",
        "displayName": "",
        "operatingSystem": "",
        "browser": "Python Requests 2.26",
        "isCompliant": false,
        "isManaged": false,
        "trustType": ""
    },
    "location": {
        "city": "Eindhoven",
        "state": "Noord-Brabant",
        "countryOrRegion": "NL",
        "geoCoordinates": {
            "altitude": null,
            "latitude": 51.43649,
            "longitude": 5.48141
        }
    },
    "appliedConditionalAccessPolicies": [],
    "authenticationContextClassReferences": [],
    "authenticationProcessingDetails": [
        {
            "key": "Root Key Type",
            "value": "Unknown"
        }
    ],
    "networkLocationDetails": [],
    "authenticationDetails": [
        {
            "authenticationStepDateTime": "2022-06-30T09:33:27Z",
            "authenticationMethod": "Password",
            "authenticationMethodDetail": "Password in the cloud",
            "succeeded": false,
            "authenticationStepResultDetail": "Invalid username or password or Invalid on-premise username or password.",
            "authenticationStepRequirement": ""
        }
    ],
    "authenticationRequirementPolicies": [],
    "sessionLifetimePolicies": [],
    "privateLinkDetails": {
        "policyId": "",
        "policyName": "",
        "resourceId": "",
        "policyTenantId": ""
    }
},
{
    "id": "515a3df8-ed8b-4388-a77f-644fbafd3b00",
    "createdDateTime": "2022-06-30T09:33:23Z",
    "userDisplayName": "Attacker",
    "userPrincipalName": "attacker@securathesis.onmicrosoft.com",
    "userId": "30a6c29d-de7c-4830-815f-9b3bb366e975",
    "appId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "appDisplayName": "Microsoft Azure CLI",
    "ipAddress": "<Redacted>",
    "ipAddressFromResourceProvider": null,
    "clientAppUsed": "Mobile Apps and Desktop clients",
    "userAgent": "python-requests/2.26.0",
    "correlationId": "61316a4b-f845-46ac-bef8-cf7223f6eafc",
    "conditionalAccessStatus": "notApplied",
    "originalRequestId": "",
    "isInteractive": true,
    "tokenIssuerName": "",
    "tokenIssuerType": "AzureAD",
    "clientCredentialType": "none",
    "processingTimeInMilliseconds": 166,
    "riskDetail": "hidden",
    "riskLevelAggregated": "hidden",
    "riskLevelDuringSignIn": "hidden",
    "riskState": "none",
    "riskEventTypes_v2": [],
    "resourceDisplayName": "Windows Azure Service Management API",
    "resourceId": "797f4846-ba00-4fd7-ba43-dac1f8f63013",
    "resourceTenantId": "d2af6ef7-a00c-438f-903b-65592cfddc48",
    "homeTenantId": "d2af6ef7-a00c-438f-903b-65592cfddc48",
    "homeTenantName": "",
    "authenticationMethodsUsed": [],
    "authenticationRequirement": "singleFactorAuthentication",
    "signInIdentifier": "attacker@securathesis.onmicrosoft.com",
    "signInIdentifierType": null,
    "servicePrincipalName": null,
    "signInEventTypes": [
        "interactiveUser"
    ],
    "servicePrincipalId": "",
    "federatedCredentialId": null,
    "userType": "member",
    "flaggedForReview": false,
    "isTenantRestricted": false,
    "autonomousSystemNumber": 12859,
    "crossTenantAccessType": "none",
    "servicePrincipalCredentialKeyId": null,
    "servicePrincipalCredentialThumbprint": "",
    "uniqueTokenIdentifier": "NTE1YTNkZjgtZWQ4Yi00Mzg4LWE3N2YtNjQ0ZmJhZmQzYjAw",
    "incomingTokenType": "none",
    "authenticationProtocol": "none",
    "resourceServicePrincipalId": "342a9ec4-8650-445e-ac63-489df0a9e524",
    "mfaDetail": null,
    "status": {
        "errorCode": 50126,
        "failureReason": "Error validating credentials due to invalid username or password.",
        "additionalDetails": "The user didn't enter the right credentials.  It's expected to see some number of these errors in your logs due to users making mistakes."
    },
    "deviceDetail": {
        "deviceId": "",
        "displayName": "",
        "operatingSystem": "",
        "browser": "Python Requests 2.26",
        "isCompliant": false,
        "isManaged": false,
        "trustType": ""
    },
    "location": {
        "city": "Eindhoven",
        "state": "Noord-Brabant",
        "countryOrRegion": "NL",
        "geoCoordinates": {
            "altitude": null,
            "latitude": 51.43649,
            "longitude": 5.48141
        }
    },
    "appliedConditionalAccessPolicies": [],
    "authenticationContextClassReferences": [],
    "authenticationProcessingDetails": [
        {
            "key": "Root Key Type",
            "value": "Unknown"
        }
    ],
    "networkLocationDetails": [],
    "authenticationDetails": [
        {
            "authenticationStepDateTime": "2022-06-30T09:33:23Z",
            "authenticationMethod": "Password",
            "authenticationMethodDetail": "Password in the cloud",
            "succeeded": false,
            "authenticationStepResultDetail": "Invalid username or password or Invalid on-premise username or password.",
            "authenticationStepRequirement": ""
        }
    ],
    "authenticationRequirementPolicies": [],
    "sessionLifetimePolicies": [],
    "privateLinkDetails": {
        "policyId": "",
        "policyName": "",
        "resourceId": "",
        "policyTenantId": ""
    }
}